# Site settings
title:       Портфолио Юрия Савина
email:       contact@megoru.ru
author:      Юрия Савина
description: "Портфолио Юрия Савина"
baseurl:     ""
url:         "http://megoru.github.io"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    truea
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

site:
  email: xoqovojz
# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: megoru
bitbucket_username:
stackoverflow_id:
twitter_username:
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
instagram_username: mego_RU

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: '↑ выше'
    older: '↓ ниже'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Спасибо, что написали мне. Скоро я отвечу вам.'
  og_locale: 'ru_RU'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'fenced_code_blocks']
#permalink:    pretty
permalink:    "/:title/"
paginate:     7
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
